version: "3.1"

services:
  sme-worker-rabbit:
    container_name: sme-worker-rabbit
    restart: on-failure
    image: sme-worker-rabbit
    build:
      context: .
      dockerfile: ./src/SME.SGP.Worker.Rabbit/Dockerfile
    env_file:
      - sme-api.env
    networks:
      - sme-network
networks:
  sme-network:
    driver: bridge
