version: "3.1"

volumes:
  postgres-data: {}

services:
  sme-webclient:
    container_name: sme-webclient
    image: sme-webclient
    build:
      context: .
      dockerfile: ./src/SME.SGP.WebClient/Dockerfile
    ports:
      - "80:80"
    networks:
      - sme-network
    environment:
      - API_URL=https://hom-novosgp.sme.prefeitura.sp.gov.br/api
      - TRACKING_ID=UA-122829830-1
networks:
  sme-network:
    driver: bridge
