name: CI
on:
  push:
    branches: [ teste ]
  pull_request:
    branches: [ teste ]

  workflow_dispatch:
  


jobs:

  tagging:
    runs-on: dotnet
    steps:
      - name: Set the value
        id: step_one
        if: endsWith(github.ref, '/teste')
        run: |
          echo "image_tag=dev" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.image_tag }}"

  backend:
    runs-on: dotnet
    needs: tagging
    steps:
      - name: Use the value
        run: |
          echo "${{ env.image_tag }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: | 
          git status
          docker build -t luizhpriotto/sme-sgp-backend:dev -f src/SME.SGP.Api/Dockerfile .
          docker push luizhpriotto/sme-sgp-backend:dev 

  workerservice:
    runs-on: dotnet
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
        name: Checkout

      # Runs a single command using the runners shell
      - name: Docker Build
        run: | 
          git status
          docker build -t luizhpriotto/sme-workerservice:dev -f src/SME.SGP.WorkerService/Dockerfile .
          docker push luizhpriotto/sme-workerservice:dev 

  workerrabbit:
    runs-on: dotnet
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2
        name: Checkout

      - name: Docker Build
        run: | 
          git status
          docker build -t luizhpriotto/sme-worker-rabbit:dev -f src/SME.SGP.Worker.Rabbbit/Dockerfile .
          docker push luizhpriotto/sme-worker-rabbit:dev
          
  flyway:
    runs-on: dotnet
    environment:
      name: hom
    needs: [ backend, workerservice, workerrabbit ]
    steps:
    - name: Executando Scripts
      env:
          USER_DB: ${{ secrets.USER_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
          URL_DB: ${{ secrets.URL_DB }}
      run: docker run --rm -v $PWD/scripts:/flyway/sql boxfuse/flyway:5.2.4 -user=$USER_DB -password=$PASSWORD_DB -url=$URL_DB -outOfOrder=true migrate
      
  deploy-dev:
    runs-on: dotnet
    environment:
      name: $MY_VAR
      url: https://dev-novosgp.sme.prefeitura.sp.gov.br
    needs: [ flyway ]
    steps:
      - name: Run an adjust of kubernetes dev
        env: # Ou como uma variável de ambiente
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
        run: |
          sed -e "s/\${RANCHER_URL}/$RANCHER_URL/" -e "s/\${RANCHER_TOKEN}/$RANCHER_TOKEN/" /runner/config_template > /runner/.kube/config
          kubectl get nodes          
      - 
       name: Change Images
       run: |
         kubectl rollout restart deployment/sme-api -n sme-novosgp
         kubectl rollout restart deployment/sme-workerservice -n sme-novosgp
         kubectl rollout restart deployment/sme-worker-rabbit -n sme-novosgp         
         rm -f /runner/.kube/config
      -
       name: Remove Images
       run: |
         docker rmi luizhpriotto/sme-workerservice:dev luizhpriotto/sme-sgp-backend:dev luizhpriotto/sme-worker-rabbit:dev
