name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ sgp ]
  pull_request:
    branches: [ sgp ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: dotnet

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run an ajdust of kubernetes dev
        env: # Ou como uma variável de ambiente
          RANCHER_URL_DEV: ${{ secrets.RANCHER_URL_DEV }}
          RANCHER_TOKEN_DEV: ${{ secrets.RANCHER_TOKEN_DEV }}
        run: |
          sed -e "s/\${RANCHER_URL}/$RANCHER_URL_DEV/" -e "s/\${RANCHER_TOKEN}/$RANCHER_TOKEN_DEV/" /runner/config_template > /runner/config
          kubectl get nodes
